services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  SchmidtWebmedia\MaskExportToContentBlocks\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
